headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\seyda\\pizza-dash-duel\\client"
publishOrigin = "config"
base = "C:\\Users\\seyda\\pizza-dash-duel\\client"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/selim/*"
to = "/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]